baseURL = "https://roytang.github.io"

[params]
    # can use markdown here
    hero_text = """**Roy Tang** is a:

- [programmer, engineer, scientist, critic, gamer, dreamer, and kid-at-heart](/2006/02/programmer-engineer-scientist-critic-gamer-dreamer-and-kid-at-heart/)
- Frustrated writer and [sketch artist](/album/sketchbook/)
- [Magic](/tags/mtg) player on weekends
- [Software developer](/tags/software-development/) since 2003. If you'd like to work with me, take a look at my [resume](/resume).

This is the off-site mirror/backup for [roytang.net](https://roytang.net). [roytang.net](https://roytang.net) is a personal site, an [E/N site](http://sawv.org/en.html), and kind of a [commonplace book](https://en.wikipedia.org/wiki/Commonplace_book); 
I post about a random assortment of topics that interest me including [software development](/tags/software-development/), [Magic the Gathering](/tags/magic-the-gathering/), [pop culture](/tags/pop-culture), [gaming](/tags/gaming), and [tech life](tags). This site is [perpetually under renovation](/2019/08/perpetually-under-renovation/).
    """

