baseURL = "https://roytang.net/"
languageCode = "en-us"
title = "Roy Tang"
theme = "exhale"

# Pagination
paginate = 20
paginatePath = "page"

# Enable Disqus integration
disqusShortname = "roytangweblog"

[taxonomies]
    tag = "tags"
    topic = "categories"

[author]
    name = "Roy Tang"
    email = "awesome@roytang.net"

[permalinks]
    post = "/:year/:month/:slug/"
    archm = "/:year/:month/"
    archy = "/:year/"    

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # You can use markdown here.
    brand = "Roy Tang"
    topimage = "![Wearing dice on my head since 2008](/uploads/diceonhead.jpg \"Wearing dice on my head since 2008\")"
    topline = "Programmer, engineer, scientist, critic, gamer, dreamer, and kid-at-heart. Randomly amazed."
    featuredImage = "https://roytang.net/uploads/diceonhead.jpg"
    description = "Roy Tang's blog. Programmer, engineer, scientist, critic, gamer, dreamer, and kid-at-heart. Randomly amazed."
    mainColor = "#004F00"
    footline = "[←](https://xn--sr8hvo.ws/%F0%9F%8D%B3%F0%9F%91%AB%E2%9E%95/previous)</a>An IndieWeb Webring 🕸💍[→](https://xn--sr8hvo.ws/%F0%9F%8D%B3%F0%9F%91%AB%E2%9E%95/next)"
    comments_enabled = true
    webmention_username = 'roytang.net'
    
    # Sidebar position
    # false, true, "left", "right"
    sidebar = "left"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "Home"

    # Select a syntax highight for highlight.js
    # Check the static/css/highlight directory for options.
    # Leave unset to fall back to default hugo highlighter instead of highlight.js
    highlight = "default"

    # Google Analytics.
    googleAnalytics = "UA-129889874-1"

    # Sidebar social links.
    github = "roytang" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "roytang" # Your LinkedIn profile ID (from public URL)
    googleplus = "" # Your Google+ profile ID
    facebook = "" # Your Facebook profile ID
    twitter = "roytang" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid
    flickr = "" # Your Flickr profile ID
    vimeo = "" # Your Vimeo profile ID

    # Sidebar RSS link: will only show up if there is a RSS feed
    # associated with the current page
    rss = true

[blackfriday]
    angledQuotes = false
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

